"""Module 4: 3DReconstruction (TRELLIS).

For each masked RGB image, runs TRELLIS to generate a 3D mesh in canonical
frame (no alignment). Outputs both a GLB for visualization and a raw NPZ
(vertices + faces) for the registration module.

This module is an orchestrator that calls the appropriate worker subprocess
(sam3d_batch_worker.py for TRELLIS1, trellis2_worker.py for TRELLIS2) in the
correct conda environment.

Usage:
    python modules/reconstruction_3d.py \\
        --input-manifest <output/recognize/recognize_manifest.json> \\
        --scene-image <target.jpg> \\
        --output-dir <output/3d_reconstruction/> \\
        --trellis-version 1

Output:
    reconstruction_3d_manifest.json — manifest listing reconstructed objects
    {name}.glb                     — canonical-frame GLB mesh
    {name}_mesh.npz                — raw vertices + faces (for alignment)

Conda env: agent (orchestrator), spawns sam3d_py311 or trellis2 subprocess

Note on NPZ files: numpy's savez/load is used (NOT pickle). The checkpoint
NPZ files are generated by our own sam3d_batch_worker and contain only
float32/int32 numeric arrays. This is safe — no arbitrary code execution risk.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parent.parent.resolve()

TAG = "[3D_RECONSTRUCTION]"


def get_python_path(env_name: str) -> str:
    """Get conda env python path."""
    if sys.platform == "win32":
        candidates = [
            Path.home() / "miniconda3" / "envs" / env_name / "python.exe",
            Path.home() / "miniconda3" / "envs" / env_name / "Scripts" / "python.exe",
        ]
    else:
        candidates = [
            Path.home() / "miniconda3" / "envs" / env_name / "bin" / "python",
        ]
    for p in candidates:
        if p.exists():
            return str(p)
    return "python"


def reconstruct_trellis1(manifest_data: dict, scene_image: str,
                         output_dir: str) -> dict:
    """Run TRELLIS1 batch reconstruction.

    Uses sam3d_batch_worker.py which loads the TRELLIS1 pipeline once and
    processes all objects. The batch worker runs layout_post_optimization
    internally (we intercept via checkpoint saving), but we only use the
    raw mesh output — alignment is the 2D3DRegistration module's job.
    """
    config_path = str(ROOT / "utils" / "third_party" / "sam3d" / "checkpoints" /
                      "hf" / "checkpoints" / "pipeline.yaml")

    objects = manifest_data["objects"]
    image_path = manifest_data["image"]

    # Build batch worker manifest
    batch_manifest = {
        "config": config_path,
        "scene_image": scene_image,
        "objects": [],
    }

    for obj in objects:
        name = obj["name"]
        batch_manifest["objects"].append({
            "name": name,
            "image": image_path,
            "mask": obj["npy_path"],
            "glb": os.path.join(output_dir, f"{name}.glb"),
            "info": os.path.join(output_dir, f"{name}_info.json"),
            "checkpoint": os.path.join(output_dir, f"{name}_checkpoint.npz"),
        })

    manifest_path = os.path.join(output_dir, "batch_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(batch_manifest, f, indent=2)

    log_path = os.path.join(output_dir, "trellis1_batch.log")
    sam3d_python = get_python_path("sam3d_py311")
    cmd = [
        sam3d_python, "-u",
        str(ROOT / "tools" / "sam3d" / "sam3d_batch_worker.py"),
        "--manifest", manifest_path,
    ]

    print(f"{TAG} Running TRELLIS1 batch ({len(objects)} objects)...")
    print(f"{TAG} Log: {log_path}")

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["LIDRA_SKIP_INIT"] = "1"
    conda_prefix = os.path.dirname(os.path.dirname(sam3d_python))
    env["CONDA_PREFIX"] = conda_prefix

    start = time.time()
    with open(log_path, "w", encoding="utf-8") as lf:
        result = subprocess.run(
            cmd, cwd=str(ROOT), text=True,
            stdin=subprocess.DEVNULL, stdout=lf, stderr=subprocess.STDOUT, env=env,
        )
    elapsed = time.time() - start

    if result.returncode != 0:
        print(f"{TAG} TRELLIS1 batch FAILED (exit {result.returncode}, {elapsed:.1f}s)")
        print(f"{TAG} Check log: {log_path}")

    # Collect results: extract raw mesh from checkpoints.
    # NPZ files here contain only numpy float32/int32 arrays (vertices, faces).
    results = {}
    for obj in objects:
        name = obj["name"]
        glb_path = os.path.join(output_dir, f"{name}.glb")
        ckpt_path = os.path.join(output_dir, f"{name}_checkpoint.npz")
        mesh_npz_path = os.path.join(output_dir, f"{name}_mesh.npz")

        if os.path.exists(ckpt_path):
            ckpt = np.load(ckpt_path)
            if "vertices" in ckpt and "faces" in ckpt:
                np.savez(mesh_npz_path,
                         vertices=ckpt["vertices"],
                         faces=ckpt["faces"])
                results[name] = {
                    "glb_path": glb_path if os.path.exists(glb_path) else None,
                    "mesh_path": mesh_npz_path,
                    "vertices_count": int(ckpt["vertices"].shape[0]),
                    "faces_count": int(ckpt["faces"].shape[0]),
                }
                glb_mb = os.path.getsize(glb_path) / (1024*1024) if os.path.exists(glb_path) else 0
                print(f"{TAG} {name}: OK ({results[name]['vertices_count']} verts, "
                      f"{results[name]['faces_count']} faces, GLB {glb_mb:.1f}MB)")
            else:
                print(f"{TAG} {name}: checkpoint missing vertices/faces")
                results[name] = None
        else:
            print(f"{TAG} {name}: FAILED (no checkpoint)")
            results[name] = None

    print(f"{TAG} TRELLIS1 batch completed in {elapsed:.1f}s ({elapsed/60:.1f} min)")
    return results


def reconstruct_trellis2(manifest_data: dict, output_dir: str) -> dict:
    """Run TRELLIS2 reconstruction.

    Uses trellis2_worker.py which runs in the trellis2 conda environment.
    """
    objects = manifest_data["objects"]

    # Build TRELLIS2 worker manifest
    t2_manifest = {"objects": []}
    for obj in objects:
        name = obj["name"]
        t2_manifest["objects"].append({
            "name": name,
            "image": obj["png_path"],  # RGBA masked image
            "glb": os.path.join(output_dir, f"{name}.glb"),
            "mesh": os.path.join(output_dir, f"{name}_mesh.npz"),
        })

    manifest_path = os.path.join(output_dir, "trellis2_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(t2_manifest, f, indent=2)

    log_path = os.path.join(output_dir, "trellis2.log")
    trellis2_python = get_python_path("trellis2")
    cmd = [
        trellis2_python, "-u",
        str(ROOT / "tools" / "sam3d" / "trellis2_worker.py"),
        "--manifest", manifest_path,
    ]

    print(f"{TAG} Running TRELLIS2 ({len(objects)} objects)...")
    print(f"{TAG} Log: {log_path}")

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["OPENCV_IO_ENABLE_OPENEXR"] = "1"
    env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

    start = time.time()
    with open(log_path, "w", encoding="utf-8") as lf:
        result = subprocess.run(
            cmd, cwd=str(ROOT), text=True,
            stdin=subprocess.DEVNULL, stdout=lf, stderr=subprocess.STDOUT, env=env,
        )
    elapsed = time.time() - start

    if result.returncode != 0:
        print(f"{TAG} TRELLIS2 FAILED (exit {result.returncode}, {elapsed:.1f}s)")
        print(f"{TAG} Check log: {log_path}")

    # Collect results. NPZ files contain only numpy numeric arrays.
    results = {}
    for obj in objects:
        name = obj["name"]
        glb_path = os.path.join(output_dir, f"{name}.glb")
        mesh_path = os.path.join(output_dir, f"{name}_mesh.npz")

        if os.path.exists(mesh_path):
            data = np.load(mesh_path)
            results[name] = {
                "glb_path": glb_path if os.path.exists(glb_path) else None,
                "mesh_path": mesh_path,
                "vertices_count": int(data["vertices"].shape[0]),
                "faces_count": int(data["faces"].shape[0]),
            }
            glb_mb = os.path.getsize(glb_path) / (1024*1024) if os.path.exists(glb_path) else 0
            print(f"{TAG} {name}: OK ({results[name]['vertices_count']} verts, "
                  f"{results[name]['faces_count']} faces, GLB {glb_mb:.1f}MB)")
        else:
            print(f"{TAG} {name}: FAILED (no mesh output)")
            results[name] = None

    print(f"{TAG} TRELLIS2 completed in {elapsed:.1f}s ({elapsed/60:.1f} min)")
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Module 4: 3D Reconstruction (TRELLIS)")
    parser.add_argument("--input-manifest", required=True,
                        help="Path to recognize_manifest.json from Module 2")
    parser.add_argument("--scene-image", default=None,
                        help="Scene image for TRELLIS1 (defaults to manifest image)")
    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--trellis-version", choices=["1", "2"], default="1",
                        help="TRELLIS version (1 or 2)")
    args = parser.parse_args()

    output_dir = os.path.abspath(args.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    # Read recognize manifest
    with open(args.input_manifest, "r", encoding="utf-8") as f:
        rec_manifest = json.load(f)

    scene_image = args.scene_image or rec_manifest["image"]
    print(f"{TAG} Input manifest: {args.input_manifest}")
    print(f"{TAG} TRELLIS version: {args.trellis_version}")
    print(f"{TAG} {len(rec_manifest['objects'])} objects to reconstruct")

    # Run reconstruction
    if args.trellis_version == "1":
        results = reconstruct_trellis1(rec_manifest, scene_image, output_dir)
    else:
        results = reconstruct_trellis2(rec_manifest, output_dir)

    # Build manifest
    obj_entries = []
    for obj in rec_manifest["objects"]:
        name = obj["name"]
        r = results.get(name)
        if r and r.get("mesh_path"):
            obj_entries.append({
                "name": name,
                "glb_path": r["glb_path"],
                "mesh_path": r["mesh_path"],
                "vertices_count": r["vertices_count"],
                "faces_count": r["faces_count"],
            })

    manifest = {
        "trellis_version": args.trellis_version,
        "objects": obj_entries,
    }
    manifest_path = os.path.join(output_dir, "reconstruction_3d_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    success = len(obj_entries)
    total = len(rec_manifest["objects"])
    print(f"\n{TAG} Done: {success}/{total} objects reconstructed")
    print(f"{TAG} Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
