"""Module 4: 3DReconstruction (TRELLIS).

For each masked RGB image, runs TRELLIS to generate a 3D mesh in canonical
frame (no alignment). Outputs both a GLB (with vertex colors) for visualization
and a raw NPZ (vertices + faces + vertex_colors) for the registration module.

Supports --max-faces for mesh decimation to speed up downstream processing.

This module is an orchestrator that calls the appropriate worker subprocess
(sam3d_batch_worker.py for TRELLIS1, trellis2_worker.py for TRELLIS2) in the
correct conda environment.

Usage:
    python modules/reconstruction_3d.py \\
        --input-manifest <output/recognize/recognize_manifest.json> \\
        --scene-image <target.jpg> \\
        --output-dir <output/3d_reconstruction/> \\
        --trellis-version 1 \\
        --max-faces 10000

Output:
    reconstruction_3d_manifest.json — manifest listing reconstructed objects
    {name}.glb                     — canonical-frame GLB mesh (with vertex colors)
    {name}_mesh.npz                — vertices + faces + vertex_colors (for alignment)

Conda env: agent (orchestrator), spawns sam3d_py311 or trellis2 subprocess

Note on NPZ files: numpy's savez/load is used (NOT pickle). The checkpoint
NPZ files are generated by our own sam3d_batch_worker and contain only
float32/int32/uint8 numeric arrays. This is safe — no arbitrary code execution risk.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parent.parent.resolve()

TAG = "[3D_RECONSTRUCTION]"


def decimate_mesh(vertices: np.ndarray, faces: np.ndarray,
                  vertex_colors: np.ndarray = None,
                  max_faces: int = 10000) -> tuple:
    """Decimate a mesh to at most max_faces using Open3D quadric decimation.

    Returns (vertices, faces, vertex_colors) — vertex_colors may be None.
    Falls back to uniform subsampling if Open3D is unavailable.
    """
    if faces.shape[0] <= max_faces:
        return vertices, faces, vertex_colors

    try:
        import open3d as o3d
        mesh_o3d = o3d.geometry.TriangleMesh()
        mesh_o3d.vertices = o3d.utility.Vector3dVector(vertices.astype(np.float64))
        mesh_o3d.triangles = o3d.utility.Vector3iVector(faces.astype(np.int32))
        if vertex_colors is not None and len(vertex_colors) == len(vertices):
            # Open3D expects colors in [0, 1] float64
            vc_float = vertex_colors[:, :3].astype(np.float64) / 255.0
            mesh_o3d.vertex_colors = o3d.utility.Vector3dVector(vc_float)

        decimated = mesh_o3d.simplify_quadric_decimation(max_faces)
        new_verts = np.asarray(decimated.vertices, dtype=np.float32)
        new_faces = np.asarray(decimated.triangles, dtype=np.int32)
        new_vc = None
        if decimated.has_vertex_colors():
            new_vc = (np.asarray(decimated.vertex_colors) * 255).astype(np.uint8)
            # Add alpha channel
            alpha = np.full((new_vc.shape[0], 1), 255, dtype=np.uint8)
            new_vc = np.hstack([new_vc, alpha])

        print(f"{TAG}   Decimated: {faces.shape[0]} -> {new_faces.shape[0]} faces, "
              f"{vertices.shape[0]} -> {new_verts.shape[0]} verts")
        return new_verts, new_faces, new_vc

    except ImportError:
        # Fallback: uniform face subsampling (loses vertex colors)
        indices = np.linspace(0, faces.shape[0] - 1, max_faces, dtype=int)
        sub_faces = faces[indices]
        used_verts = np.unique(sub_faces.ravel())
        vert_map = np.full(vertices.shape[0], -1, dtype=int)
        vert_map[used_verts] = np.arange(len(used_verts))
        new_verts = vertices[used_verts]
        new_faces = vert_map[sub_faces]
        new_vc = vertex_colors[used_verts] if vertex_colors is not None else None
        print(f"{TAG}   Subsampled (no Open3D): {faces.shape[0]} -> {new_faces.shape[0]} faces")
        return new_verts, new_faces, new_vc


def get_python_path(env_name: str) -> str:
    """Get conda env python path."""
    if sys.platform == "win32":
        candidates = [
            Path.home() / "miniconda3" / "envs" / env_name / "python.exe",
            Path.home() / "miniconda3" / "envs" / env_name / "Scripts" / "python.exe",
        ]
    else:
        candidates = [
            Path.home() / "miniconda3" / "envs" / env_name / "bin" / "python",
        ]
    for p in candidates:
        if p.exists():
            return str(p)
    return "python"


def reconstruct_trellis1(manifest_data: dict, scene_image: str,
                         output_dir: str, max_faces: int = 0) -> dict:
    """Run TRELLIS1 batch reconstruction.

    Uses sam3d_batch_worker.py which loads the TRELLIS1 pipeline once and
    processes all objects. The batch worker runs layout_post_optimization
    internally (we intercept via checkpoint saving), but we only use the
    raw mesh output — alignment is the 2D3DRegistration module's job.
    """
    config_path = str(ROOT / "utils" / "third_party" / "sam3d" / "checkpoints" /
                      "hf" / "checkpoints" / "pipeline.yaml")

    objects = manifest_data["objects"]
    image_path = manifest_data["image"]

    # Build batch worker manifest
    batch_manifest = {
        "config": config_path,
        "scene_image": scene_image,
        "objects": [],
    }

    for obj in objects:
        name = obj["name"]
        batch_manifest["objects"].append({
            "name": name,
            "image": image_path,
            "mask": obj["npy_path"],
            "glb": os.path.join(output_dir, f"{name}.glb"),
            "canonical_glb": os.path.join(output_dir, f"{name}_canonical.glb"),
            "info": os.path.join(output_dir, f"{name}_info.json"),
            "checkpoint": os.path.join(output_dir, f"{name}_checkpoint.npz"),
        })

    manifest_path = os.path.join(output_dir, "batch_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(batch_manifest, f, indent=2)

    log_path = os.path.join(output_dir, "trellis1_batch.log")
    sam3d_python = get_python_path("sam3d_py311")
    cmd = [
        sam3d_python, "-u",
        str(ROOT / "tools" / "sam3d" / "sam3d_batch_worker.py"),
        "--manifest", manifest_path,
    ]

    print(f"{TAG} Running TRELLIS1 batch ({len(objects)} objects)...")
    print(f"{TAG} Log: {log_path}")

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["LIDRA_SKIP_INIT"] = "1"
    conda_prefix = os.path.dirname(os.path.dirname(sam3d_python))
    env["CONDA_PREFIX"] = conda_prefix

    start = time.time()
    with open(log_path, "w", encoding="utf-8") as lf:
        result = subprocess.run(
            cmd, cwd=str(ROOT), text=True,
            stdin=subprocess.DEVNULL, stdout=lf, stderr=subprocess.STDOUT, env=env,
        )
    elapsed = time.time() - start

    if result.returncode != 0:
        print(f"{TAG} TRELLIS1 batch FAILED (exit {result.returncode}, {elapsed:.1f}s)")
        print(f"{TAG} Check log: {log_path}")

    # Collect results: extract raw mesh + vertex colors from checkpoints.
    # NPZ files contain only numpy float32/int32/uint8 arrays.
    results = {}
    for obj in objects:
        name = obj["name"]
        glb_path = os.path.join(output_dir, f"{name}.glb")
        ckpt_path = os.path.join(output_dir, f"{name}_checkpoint.npz")
        mesh_npz_path = os.path.join(output_dir, f"{name}_mesh.npz")

        if os.path.exists(ckpt_path):
            ckpt = np.load(ckpt_path)
            if "vertices" in ckpt and "faces" in ckpt:
                verts = ckpt["vertices"]
                faces = ckpt["faces"]
                vc = ckpt["vertex_colors"] if "vertex_colors" in ckpt else None

                # Decimate if requested
                if max_faces > 0:
                    verts, faces, vc = decimate_mesh(verts, faces, vc, max_faces)

                save_dict = {"vertices": verts, "faces": faces}
                if vc is not None:
                    save_dict["vertex_colors"] = vc
                # Preserve TRELLIS SS initial pose for registration module.
                # The SS stage predicts rotation/translation/scale which are
                # far better initial guesses than identity rotation.
                for key in ("rotation", "translation", "scale"):
                    if key in ckpt:
                        save_dict[key] = ckpt[key]
                np.savez(mesh_npz_path, **save_dict)

                canonical_glb = os.path.join(output_dir, f"{name}_canonical.glb")
                results[name] = {
                    "glb_path": glb_path if os.path.exists(glb_path) else None,
                    "canonical_glb_path": canonical_glb if os.path.exists(canonical_glb) else None,
                    "mesh_path": mesh_npz_path,
                    "checkpoint_path": ckpt_path,
                    "vertices_count": int(verts.shape[0]),
                    "faces_count": int(faces.shape[0]),
                    "has_colors": vc is not None,
                }
                glb_mb = os.path.getsize(glb_path) / (1024*1024) if os.path.exists(glb_path) else 0
                color_str = "with colors" if vc is not None else "no colors"
                canonical_str = "canonical OK" if results[name]["canonical_glb_path"] else "no canonical"
                print(f"{TAG} {name}: OK ({results[name]['vertices_count']} verts, "
                      f"{results[name]['faces_count']} faces, {color_str}, {canonical_str}, GLB {glb_mb:.1f}MB)")
            else:
                print(f"{TAG} {name}: checkpoint missing vertices/faces")
                results[name] = None
        else:
            print(f"{TAG} {name}: FAILED (no checkpoint)")
            results[name] = None

    print(f"{TAG} TRELLIS1 batch completed in {elapsed:.1f}s ({elapsed/60:.1f} min)")
    return results


def reconstruct_trellis2(manifest_data: dict, output_dir: str,
                         max_faces: int = 0) -> dict:
    """Run TRELLIS2 reconstruction.

    Uses trellis2_worker.py which runs in the trellis2 conda environment.
    """
    objects = manifest_data["objects"]

    # Build TRELLIS2 worker manifest
    t2_manifest = {"objects": []}
    for obj in objects:
        name = obj["name"]
        t2_manifest["objects"].append({
            "name": name,
            "image": obj["png_path"],  # RGBA masked image
            "glb": os.path.join(output_dir, f"{name}.glb"),
            "mesh": os.path.join(output_dir, f"{name}_mesh.npz"),
        })

    manifest_path = os.path.join(output_dir, "trellis2_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(t2_manifest, f, indent=2)

    log_path = os.path.join(output_dir, "trellis2.log")
    trellis2_python = get_python_path("trellis2")
    cmd = [
        trellis2_python, "-u",
        str(ROOT / "tools" / "sam3d" / "trellis2_worker.py"),
        "--manifest", manifest_path,
    ]

    print(f"{TAG} Running TRELLIS2 ({len(objects)} objects)...")
    print(f"{TAG} Log: {log_path}")

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["OPENCV_IO_ENABLE_OPENEXR"] = "1"
    env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

    start = time.time()
    with open(log_path, "w", encoding="utf-8") as lf:
        result = subprocess.run(
            cmd, cwd=str(ROOT), text=True,
            stdin=subprocess.DEVNULL, stdout=lf, stderr=subprocess.STDOUT, env=env,
        )
    elapsed = time.time() - start

    if result.returncode != 0:
        print(f"{TAG} TRELLIS2 FAILED (exit {result.returncode}, {elapsed:.1f}s)")
        print(f"{TAG} Check log: {log_path}")

    # Collect results. NPZ files contain only numpy numeric arrays.
    results = {}
    for obj in objects:
        name = obj["name"]
        glb_path = os.path.join(output_dir, f"{name}.glb")
        mesh_path = os.path.join(output_dir, f"{name}_mesh.npz")

        if os.path.exists(mesh_path):
            data = np.load(mesh_path)
            verts = data["vertices"]
            faces = data["faces"]
            vc = data["vertex_colors"] if "vertex_colors" in data else None

            # Decimate if requested
            if max_faces > 0:
                verts, faces, vc = decimate_mesh(verts, faces, vc, max_faces)
                save_dict = {"vertices": verts, "faces": faces}
                if vc is not None:
                    save_dict["vertex_colors"] = vc
                np.savez(mesh_path, **save_dict)

            results[name] = {
                "glb_path": glb_path if os.path.exists(glb_path) else None,
                "mesh_path": mesh_path,
                "vertices_count": int(verts.shape[0]),
                "faces_count": int(faces.shape[0]),
                "has_colors": vc is not None,
            }
            glb_mb = os.path.getsize(glb_path) / (1024*1024) if os.path.exists(glb_path) else 0
            color_str = "with colors" if vc is not None else "no colors"
            print(f"{TAG} {name}: OK ({results[name]['vertices_count']} verts, "
                  f"{results[name]['faces_count']} faces, {color_str}, GLB {glb_mb:.1f}MB)")
        else:
            print(f"{TAG} {name}: FAILED (no mesh output)")
            results[name] = None

    print(f"{TAG} TRELLIS2 completed in {elapsed:.1f}s ({elapsed/60:.1f} min)")
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Module 4: 3D Reconstruction (TRELLIS)")
    parser.add_argument("--input-manifest", required=True,
                        help="Path to recognize_manifest.json from Module 2")
    parser.add_argument("--scene-image", default=None,
                        help="Scene image for TRELLIS1 (defaults to manifest image)")
    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--trellis-version", choices=["1", "2"], default="1",
                        help="TRELLIS version (1 or 2)")
    parser.add_argument("--max-faces", type=int, default=0,
                        help="Max faces per mesh (0 = no decimation, e.g. 10000)")
    args = parser.parse_args()

    output_dir = os.path.abspath(args.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    # Read recognize manifest
    with open(args.input_manifest, "r", encoding="utf-8") as f:
        rec_manifest = json.load(f)

    scene_image = args.scene_image or rec_manifest["image"]
    print(f"{TAG} Input manifest: {args.input_manifest}")
    print(f"{TAG} TRELLIS version: {args.trellis_version}")
    print(f"{TAG} Max faces: {args.max_faces if args.max_faces > 0 else 'unlimited'}")
    print(f"{TAG} {len(rec_manifest['objects'])} objects to reconstruct")

    # Run reconstruction
    if args.trellis_version == "1":
        results = reconstruct_trellis1(rec_manifest, scene_image, output_dir,
                                       max_faces=args.max_faces)
    else:
        results = reconstruct_trellis2(rec_manifest, output_dir,
                                       max_faces=args.max_faces)

    # Build manifest
    obj_entries = []
    for obj in rec_manifest["objects"]:
        name = obj["name"]
        r = results.get(name)
        if r and r.get("mesh_path"):
            entry = {
                "name": name,
                "glb_path": r["glb_path"],
                "mesh_path": r["mesh_path"],
                "vertices_count": r["vertices_count"],
                "faces_count": r["faces_count"],
                "has_colors": r.get("has_colors", False),
            }
            if r.get("canonical_glb_path"):
                entry["canonical_glb_path"] = r["canonical_glb_path"]
            if r.get("checkpoint_path"):
                entry["checkpoint_path"] = r["checkpoint_path"]
            obj_entries.append(entry)

    manifest = {
        "trellis_version": args.trellis_version,
        "objects": obj_entries,
    }
    manifest_path = os.path.join(output_dir, "reconstruction_3d_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    success = len(obj_entries)
    total = len(rec_manifest["objects"])
    print(f"\n{TAG} Done: {success}/{total} objects reconstructed")
    print(f"{TAG} Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
